### ISSUE TITLE
Incorrect shader path when importing package

### ISSUE THREAD

**Issue by noebm** [Neopallium/bevy_water#3]
Hello!
When importing the package I had to copy the shaders into my projects `assets` directory.
This seems to be because the shaders are only imported at runtime and bevy uses the environment set up by cargo to infer the correct paths.
Loading the shaders via `load_internal_asset` worked for me.

**Comment by Neopallium** [comment]
Thank!

I added a feature flag `embed_shaders` that is enabled by default.  Disabling that feature will allow hot-reloading to work (`load_internal_asset` doesn't support hot-reloading) and/or allow customized water shader.

The current water shader might not match the style others want and they might want to copy the shader into their assets to customize it.  The noise shaders are still embedded and don't need to be copied.

I just published a new version `0.10.3` with your change.
